export const sliderData = [
  {
    title: 'Sloko',
    image: require('./../assets/images/homescreen/sloko-img.png'),
  },
];

export const paidGames = [
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Spider-Man',
    subtitle: 'Marvel',
    stats: 'No',
    sending: '$25.99',
    id: '1',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Battlefield 2042',
    subtitle: 'EA',
    stats: 'No',
    sending: '$19.99',
    id: '2',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Spider-Man: Miles Morales',
    subtitle: 'Marvel',
    stats: 'No',
    sending: '$29.99',
    id: '3',
  },
  {
    poster: require('../assets/images/halo-infinite.jpeg'),
    title: 'Halo Infinite',
    subtitle: 'Xbox Game',
    stats: 'No',
    sending: '$24.99',
    id: '4',
  },
  {
    poster: require('../assets/images/FarCry6.png'),
    title: 'Far Cry 6',
    subtitle: 'Ubisoft',
    stats: 'No',
    sending: '$15.99',
    id: '5',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'God of War: Ragnarok',
    subtitle: 'Sony',
    stats: 'No',
    sending: '$25.99',
    id: '6',
  },
];

export const detailList = [
  {
    poster: require('../assets/images/default-img.png'),
    deskripsi: 'Deskripsi1',
    IRMnumber: '16714366811',
    kodeAsset: 'Kode Asset1',
    departemen: 'Departemen1',
    date: '15-12-2022',
    stats: 'Yes',
    sending: require('../assets/images/sending.png'),
    id: '1',
  },
  {
    poster: require('../assets/images/default-img.png'),
    deskripsi: 'Deskripsi2',
    IRMnumber: '17716166811',
    kodeAsset: 'Kode Asset2',
    departemen: 'Departemen2',
    date: '13-12-2022',
    stats: 'Yes',
    sending: require('../assets/images/sending.png'),
    id: '2',
  },
  {
    poster: require('../assets/images/default-img.png'),
    deskripsi: 'Deskripsi3',
    IRMnumber: '18716166811',
    kodeAsset: 'Kode Asset3',
    departemen: 'Departemen3',
    date: '12-12-2022',
    stats: 'Yes',
    sending: require('../assets/images/sending.png'),
    id: '3',
  },
  {
    poster: require('../assets/images/default-img.png'),
    deskripsi: 'Deskripsi4',
    IRMnumber: '19716166811',
    kodeAsset: 'Kode Asset4',
    departemen: 'Departemen4',
    date: '9-12-2022',
    stats: 'No',
    sending: require('../assets/images/sending.png'),
    id: '4',
  },
  {
    poster: require('../assets/images/default-img.png'),
    deskripsi: 'Deskripsi5',
    IRMnumber: '20716166811',
    kodeAsset: 'Kode Asset5',
    departemen: 'Departemen5',
    date: '11-12-2022',
    stats: 'Yes',
    sending: require('../assets/images/sending.png'),
    id: '5',
  },
  {
    poster: require('../assets/images/default-img.png'),
    deskripsi: 'Deskripsi6',
    IRMnumber: '21716166811',
    kodeAsset: 'Kode Asset6',
    departemen: 'Departemen6',
    date: '10-12-2022',
    stats: 'No',
    sending: require('../assets/images/sending.png'),
    id: '6',
  },
];